version: '3.9'
services:
  nginx:
    image: nginx:latest
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro/"
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./etc/nginx/certs:/etc/nginx/certs"
      - "./etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem"
      - chextip_static:/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - chextip
      - db
    restart: "always"
    networks:
      - chextip-network

  chextip:
    image: dramos777/chextip:2.7
    environment:
      SIPURL: "${SIPURL:?Please configure SIPURL in the .env file}"
      PBXUSER: "${PBXUSER:?Please configure PBXUSER in the .env file}"
      PBXPASSWORD: "${PBXPASSWORD:?Please configure PBXPASSWORD in the .env file}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:?Please configure MYSQL_DATABASE in the .env file}"
      MYSQL_USER: "${MYSQL_USER:?Please configure MYSQL_USER in the .env file}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:?Please configure MYSQL_PASSWORD in the .env file}"
      MYSQL_HOST: "${MYSQL_HOST:?Please configure MYSQL_HOST in the .env file}"
      REDIS_HOST: "${REDIS_HOST:?Please configure REDIS_HOST in the .env file}"
      REDIS_PORT: "${REDIS_PORT:?Please configure REDIS_PORT in the .env file}"
      SSH_USER: "${SSH_USER:?Please configure SSH_USER in the .env file}"
      SSH_PORT: "${SSH_PORT:?Please configure SSH_PORT in the .env file}"
      SSH_PASSWORD: "${SSH_PASSWORD:?Please configure SSH_PASSWORD in the .env file}"
      TELNET_PORT: "${TELNET_PORT:?Please configure TELNET_PORT in the .env file}"
      TELNET_PASSWORD: "${TELNET_PASSWORD:?Please configure TELNET_PASSWORD in the .env file}"
      HTTP_USER: "${HTTP_USER:?Please configure HTTP_USER in the .env file}"
      HTTP_PASSWORD: "${HTTP_PASSWORD:?Please configure HTTP_PASSWORD in the .env file}"
      HTTP_XPE3200_PASS: "${HTTP_XPE3200_PASS:?Please configure HTTP_XPE3200_PASS in the .env file}"
      HTTP_SS3530_PASS: "${HTTP_SS3530_PASS:?Please configure HTTP_SS3530_PASS in the .env file}"
      HTTP_SS3532_PASS: "${HTTP_SS3532_PASS:?Please configure HTTP_SS3532_PASS in the .env file}"
      HTTP_SS1530_PASS: "${HTTP_SS1530_PASS:?Please configure HTTP_SS1530_PASS in the .env file}"
      HTTP_SS3540_PASS: "${HTTP_SS3540_PASS:?Please configure HTTP_SS3540_PASS in the .env file}"
      HTTP_CONTROLID_IDFACEMAX_PASS: "${HTTP_CONTROLID_IDFACEMAX_PASS:?Please configure HTTP_CONTROLID_IDFACEMAX_PASS in the .env file}"
      LINEAR_USER: "${LINEAR_USER:?Please configure LINEAR_USER in the .env file}"
      LINEAR_PASSWORD: "${LINEAR_PASSWORD:?Please configure LINEAR_PASSWORD in the .env file}"
      NICE_USER: "${NICE_USER:?Please configure NICE_USER in the .env file}"
      NICE_PASSWORD: "${NICE_PASSWORD:?Please configure NICE_PASSWORD in the .env file}"
      PREFIXIP: "${PREFIXIP:?Please configure PREFIXIP in the .env file}"
#    ports:
#      - "5000:5000"
    volumes:
      - chextip_static:/app/static
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - chextip-network
    depends_on:
      - db
    restart: "always"

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE:?Please configure MYSQL_DATABASE in the .env file}"
      MYSQL_USER: "${MYSQL_USER:?Please configure MYSQL_USER in the .env file}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:?Please configure MYSQL_PASSWORD in the .env file}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?Please configure MYSQL_ROOT_PASSWORD in the .env file}"
#    ports:
#      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - chextip-network
    restart: "always"

  redis:
    image: redis:latest
    environment:
      REDIS_HOST: "${REDIS_HOST:?Please configure REDIS_HOST in the .env file}"
      REDIS_PORT: "${REDIS_PORT:?Please configure REDIS_PORT in the .env file}"
#    ports:
#      - "6379:6379"
    networks:
      - chextip-network
    restart: "always"

volumes:
  db_data:
  chextip_static:

networks:
  chextip-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
